apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-actions-deployment
  labels:
    app: rasa-actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa-actions
  template:
    metadata:
      labels:
        app: rasa-actions
    spec:
      containers:
      - name: rasa-actions
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/rasa-actions:latest
        ports:
        - containerPort: 5055
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-actions-service
spec:
  selector:
    app: rasa-actions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5055
  type: LoadBalancer