apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-deployment
  labels:
    app: rasa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
      - name: rasa
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/rasa-chatbot:latest
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: rasa-service
spec:
  selector:
    app: rasa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
  type: LoadBalancer
