name: Train Rasa Model

on:
  push:
    paths:
      - "data/**"
      - "domain.yml"
      - "config.yml"

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Rasa and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install rasa

      - name: Train Rasa Model
        run: rasa train

      - name: Upload Model
        uses: actions/upload-artifact@v3
        with:
          name: rasa-model
          path: models/
